### PR TITLE
Merge main

### PR DESCRIPTION
**Pull request by henrygerardmoore**

### CODE REVIEW

**Review by bijoua29 — APPROVED** [review]

**Comment by bijoua29** [comment]
Why is the RedHat build failing - is it failing on upstream as well?

**Comment by henrygerardmoore** [comment]
@bijoua29 looks like RHEL doesn't have `ros-rolling-diagnostic-updater` (which our fork adds as a dependency, I think): 
```
No match for argument: ros-rolling-diagnostic-updater
```

Not sure why, but since it is fine for non-RHEL, can I merge it?

**Comment by bijoua29** [comment]
> @bijoua29 looks like RHEL doesn't have `ros-rolling-diagnostic-updater` (which our fork adds as a dependency, I think):
> 
> ```
> No match for argument: ros-rolling-diagnostic-updater
> ```
> 
> Not sure why, but since it is fine for non-RHEL, can I merge it?

Are you saying our fork adds diagnostic-updater? Not sure why it would as we don't use it

**Comment by henrygerardmoore** [comment]
Hmm, I am also unsure as to why (i.e. I don't know where or if it is being used), but it indeed is added as a dependency. We can see if removing it causes any problems, it's possible it was added as a dependency while testing something out that ultimately didn't get committed or was reverted.

**Comment by bijoua29** [comment]
> Hmm, I am also unsure as to why (i.e. I don't know where or if it is being used), but it indeed is added as a dependency. We can see if removing it causes any problems, it's possible it was added as a dependency while testing something out that ultimately didn't get committed or was reverted.

Yeah, I would remove it from our fork if it was added in our fork and see if anything breaks

**Pull request merged**
